module.exports = {
  apps: [
    // ========================================
    // API Services (3)
    // ========================================
    {
      name: 'express-api',
      script: './express/build/src/index.js',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        PORT: 8000
      },
      error_file: 'express/logs/pm2-error.log',
      out_file: 'express/logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'plumber-api',
      script: 'Rscript',
      args: 'plumber/api.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '1G',
      env: {
        PORT: 8002
      },
      error_file: 'plumber/logs/plumber-error.log',
      out_file: 'plumber/logs/plumber-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'gateway',
      script: 'Rscript',
      args: 'plumber/gateway/gateway.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '1G',
      env: {
        PORT: 8003
      },
      error_file: 'plumber/logs/gateway-error.log',
      out_file: 'plumber/logs/gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },

    // ========================================
    // Strategy Bots (11)
    // ========================================
    {
      name: 'strategy-crossovers',
      script: 'Rscript',
      args: 'strategies/crossOvers.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/crossovers-error.log',
      out_file: 'strategies/logs/crossovers-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-op-probability',
      script: 'Rscript',
      args: 'strategies/OP_probability_model.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/op-probability-error.log',
      out_file: 'strategies/logs/op-probability-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-cbbtc-probability',
      script: 'Rscript',
      args: 'strategies/cbBTC_probability_model.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/cbbtc-probability-error.log',
      out_file: 'strategies/logs/cbbtc-probability-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-supertrend',
      script: 'Rscript',
      args: 'strategies/superTrend.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/supertrend-error.log',
      out_file: 'strategies/logs/supertrend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-velo1d',
      script: 'Rscript',
      args: 'strategies/Velo1DBot.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/velo1d-error.log',
      out_file: 'strategies/logs/velo1d-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-aero-ema',
      script: 'Rscript',
      args: 'strategies/aero_ema_11_33_crossover.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/aero-ema-error.log',
      out_file: 'strategies/logs/aero-ema-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-eth-ema',
      script: 'Rscript',
      args: 'strategies/eth_ema_11_33_crossover.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/eth-ema-error.log',
      out_file: 'strategies/logs/eth-ema-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-dht-ema-rsi',
      script: 'Rscript',
      args: 'strategies/dht_ema_rsi.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/dht-ema-rsi-error.log',
      out_file: 'strategies/logs/dht-ema-rsi-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-velo-ema-rsi',
      script: 'Rscript',
      args: 'strategies/velo_ema_rsi.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/velo-ema-rsi-error.log',
      out_file: 'strategies/logs/velo-ema-rsi-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-velo-rsi14',
      script: 'Rscript',
      args: 'strategies/velo_rsi_14.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/velo-rsi14-error.log',
      out_file: 'strategies/logs/velo-rsi14-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'strategy-ethusd1d',
      script: 'Rscript',
      args: 'strategies/ETHUSD1D_EMA_RSI.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'strategies/logs/ethusd1d-error.log',
      out_file: 'strategies/logs/ethusd1d-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },

    // ========================================
    // Tradebot Threads (6 main execution bots)
    // ========================================
    {
      name: 'tradebot-main',
      script: 'Rscript',
      args: 'tradebot/tradebot.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'tradebot/logs/tradebot-error.log',
      out_file: 'tradebot/logs/tradebot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'tradebot-pools',
      script: 'Rscript',
      args: 'tradebot/pools.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'tradebot/logs/pools-error.log',
      out_file: 'tradebot/logs/pools-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'tradebot-forever',
      script: 'Rscript',
      args: 'tradebot/forever.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'tradebot/logs/forever-error.log',
      out_file: 'tradebot/logs/forever-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'tradebot-defi',
      script: 'Rscript',
      args: 'tradebot/defi.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '500M',
      error_file: 'tradebot/logs/defi-error.log',
      out_file: 'tradebot/logs/defi-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'monitor-gas',
      script: 'Rscript',
      args: 'tradebot/web3.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
      error_file: 'tradebot/logs/gas-monitor-error.log',
      out_file: 'tradebot/logs/gas-monitor-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'monitor-models',
      script: 'Rscript',
      args: 'tradebot/rebalance.R',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '300M',
      error_file: 'tradebot/logs/models-error.log',
      out_file: 'tradebot/logs/models-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },

    // ========================================
    // Data Collectors (2) - MySQL: EC2, Redis: localhost
    // ========================================
    {
      name: 'collector-candles',
      script: 'python3',
      args: 'data-collectors/db/candles.py',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '200M',
      error_file: 'data-collectors/logs/candles-error.log',
      out_file: 'data-collectors/logs/candles-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    },
    {
      name: 'collector-messages',
      script: 'python3',
      args: 'data-collectors/db/messages.py',
      cwd: '/Users/richardclare/infinite-trading-api',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '200M',
      error_file: 'data-collectors/logs/messages-error.log',
      out_file: 'data-collectors/logs/messages-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s'
    }
  ]
};
