"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
gmport;
express;
from;
"express";
var admin_1 = require("./requests/admin");
var invest_1 = require("./requests/invest");
var trade_test_1 = require("./requests/trade_test");
var lending_1 = require("./requests/lending");
var app = express();
var PORT = process.env.PORT || 8005;
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(admin_1.default);
app.use(invest_1.default);
app.use(trade_test_1.default);
app.use(lending_1.default);
app.listen(PORT, function () {
    console.log("\u26A1\uFE0F[server]: Server is running on http://localhost:".concat(PORT, " ..."));
});
