name: Database Export

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Export Database
        run: |
          # Connect to MySQL and export api_tokens
          apt-get update && apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u richard_clare -pAxDWeW8E7w8dSXJKsXsdfASXaxAD279347 infinitetrading -e "SELECT token, wallet_address, encrypted_pk FROM api_tokens" > /tmp/export.txt
          cat /tmp/export.txt
